### ISSUE TITLE
Trabalho Final

### ISSUE THREAD

**Issue by jacsonrbinf** [joaopauloesper/MRS-GMJP#1]
Olá João e Gabriel!
O código parcial do Trabalho final não está no repositorio. Faça o quanto antes para acompanhamento e avaliação.
Prof Jacson

**Comment by gmfaria6** [comment]
Boa tarde professor, tudo bem?

Conversei com o João Paulo esse fim de semana e estamos com algumas dúvidas
sobre o trabalho.

Podemos marcar uma conversa hoje (qualquer horário) para sanar as dúvidas?
Ou o senhor acha melhor deixar para a aula de quinta-feira?

Abraços,
Gabriel Matheus

Em seg., 4 de out. de 2021 às 14:57, jacsonrbinf ***@***.***>
escreveu:
